FROM microsoft/dotnet-preview

# Copy the app
COPY /app /app
WORKDIR /app

# Configure the listening port to 80
ENV ASPNETCORE_SERVER.URLS http://*:80
EXPOSE 80

# Start the app
ENTRYPOINT dotnet ASPNetDevInAContainer.dll
